// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local first (for local dev), then .env as fallback.
// Next.js loads .env.local automatically at runtime, but Prisma CLI needs
// it explicitly here so `prisma migrate` / `prisma db push` work.
config({ path: ".env.local" });
config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DIRECT_URL is the unpooled Neon connection (for migrations, schema ops).
    // Falls back to DATABASE_URL if DIRECT_URL isn't set.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
